version: '3.9'

services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - ./configs/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: 'postgres -c config_file=/etc/postgresql/postgresql.conf'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      start_period: 10s