version: '3.9'

services:
  api01: &api
    build: .
    ports:
      - 8081:8080
    depends_on:
      - database
    environment:
      - PORT=8080
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=database
      - DB=db
    restart: always
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.20"
    #       memory: "30MB"

  api02:
    <<: *api
    ports:
      - 8082:8080

  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - ./configs/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: 'postgres -c config_file=/etc/postgresql/postgresql.conf'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      start_period: 10s
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.70"
    #       memory: "440MB"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.60"
    #       memory: "80MB"

networks:
  default:
    driver: bridge